### ISSUE TITLE
VBG resistor has incorrect value

### ISSUE THREAD

**Issue by ataradov** [strawberryhacker/vanilla-sbc#2]
R101 is marked as 1K. It should be 5.62K +/-1% for correct USB operation.

**Comment by ataradov** [comment]
Also, I just noticed R102. It should not be populated, otherwise your device would always erase. And then you would short the pads to erase the device.

**Comment by strawberryhacker** [comment]
Thank you for pointing this out. And thanks for the interest. This is fixed now. The R102 should be a pulldown instead; my mistake. I have testpoint for erasing.
